table DIM_Store
	lineageTag: cf0c52c9-d00d-4795-b7f2-3e98490a7e75

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 559ba8b2-87a3-4e1c-a13d-c7f5fc1ebd29
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column Store
		dataType: string
		lineageTag: b6ffaf63-5d6e-4caa-9531-c811899ffc5d
		summarizeBy: none
		sourceColumn: Store

		annotation SummarizationSetBy = Automatic

	partition DIM_Store = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\PBI Course - Anh Leimer\1. Dataset\Store.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"location_id", Int64.Type}, {"store", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"store", "Store"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

