table DIM_Product
	lineageTag: 95a6d238-8168-4af1-a618-b8ae1b44f398

	column 'Product Id'
		dataType: int64
		formatString: 0
		lineageTag: 23013ba1-3676-404e-bf83-7cbd59907193
		summarizeBy: none
		sourceColumn: Product Id

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 0b32aeea-c316-4d2e-8251-3f1b1b1fcc8a
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Product Category'
		dataType: string
		lineageTag: c2f7d4e4-e4fe-4cb3-94f1-d7b21b3aa172
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 7700c969-13d9-4a1f-ae1a-4c9008ebed68
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	partition DIM_Product = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\PBI Course - Anh Leimer\1. Dataset\Product.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_detail", type text}, {"product_category", type text}, {"product_type", type text}}),
				    #"Replace Headers" = Table.TransformColumnNames(#"Changed Type", each Text.Replace(_,"_"," ")),
				    #"Capitalize Headers" = Table.TransformColumnNames(#"Replace Headers", Text.Proper),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalize Headers",{{"Product Detail", "Product"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

