table FACT_Transaction
	lineageTag: 38cc7390-940e-471a-ba3e-19e5a32dcbdb

	column 'Transaction Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4af1239f-86d7-44bf-8546-9c6977bfc748
		summarizeBy: none
		sourceColumn: Transaction Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Transaction Time'
		dataType: dateTime
		formatString: hh:nn
		lineageTag: e975a526-6398-4217-8354-2da6020e2f1b
		summarizeBy: none
		sourceColumn: Transaction Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Store Id'
		dataType: int64
		formatString: 0
		lineageTag: cf49cf26-fb9c-465e-a868-4bc29505e609
		summarizeBy: none
		sourceColumn: Store Id

		annotation SummarizationSetBy = Automatic

	column 'Product Id'
		dataType: int64
		formatString: 0
		lineageTag: e7075725-318a-4937-bc43-6f04eb9d4ab1
		summarizeBy: none
		sourceColumn: Product Id

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: 6bbf111a-2f69-42b2-a64c-35cdfec21d74
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Transaction Qty'
		dataType: int64
		formatString: 0
		lineageTag: fc66e2f8-9fb7-4963-8665-e67bc162cd7e
		summarizeBy: sum
		sourceColumn: Transaction Qty

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 04d6253b-c167-4974-952a-0e9cb63632de
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FACT_Transaction = m
		mode: import
		source =
				let
				    Source = Folder.Files("D:\PBI Course - Anh Leimer\1. Dataset\Transaction"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"transaction_id", Int64.Type}, {"transaction_date", type date}, {"transaction_time", type time}, {"store_id", Int64.Type}, {"product_id", Int64.Type}, {"unit_price", type number}, {"transaction_qty", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name", "transaction_id"}),
				    #"Replace Headers" = Table.TransformColumnNames(#"Removed Columns", each Text.Replace(_,"_"," ")),
				    #"Capitalize Headers" = Table.TransformColumnNames(#"Replace Headers", Text.Proper),
				    #"Added Custom" = Table.AddColumn(#"Capitalize Headers", "Sales", each [Unit Price]*[Transaction Qty]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Sales", type number}}),
				    #"Calculated Start of Hour" = Table.TransformColumns(#"Changed Type1",{{"Transaction Time", Time.StartOfHour, type time}})
				in
				    #"Calculated Start of Hour"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

