table 'DIM_Job Title'
	lineageTag: 905b894d-c0bc-491a-b9bc-c0d1c9dfb88e

	column 'Job Title'
		dataType: string
		lineageTag: c0f0093c-2a2c-4422-b231-a816b1f26a2a
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"DIM_Job Title","TableItemName":"Job Title (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Job Level'
		dataType: string
		lineageTag: 41b2fbf1-6703-4512-9d8c-1ec742cd8f00
		summarizeBy: none
		sourceColumn: Job Level

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a34e6e7b-a737-4342-9db6-34c2e613e524
		summarizeBy: none
		sourceColumn: Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Clusters for Job Title
	column 'Job Title (clusters)' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE(
					'ClusterMappingTable'[ClusterId],
					'ClusterMappingTable'[Job_Title],
					'DIM_Job Title'[Job Title]
				)
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 516db8fe-f408-4cdf-9867-1d969d645f2f
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "DIM_Job Title"
				          }
				        },
				        "Property": "Job Title"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"DIM_Job Title"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Job Title"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"m","Entity":"Measure"},{"Name":"d","Entity":"DIM_Job Title"},{"Name":"d1","Entity":"DIM_Gender"},{"Name":"b","Entity":"Area_Resource Level"},{"Name":"d11","Entity":"DIM_Date"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d1"}},"Property":"Gender"}}],"Values":[[{"Literal":{"Value":"'Female'"}}]]}}}}},{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"b"}},"Property":"Fields"}}],"Values":[[{"Literal":{"Value":"'''DIM_Job Title''[Job Title]'"}}]]}}},{"Condition":{"Comparison":{"Left":{"Column":{"Expression":{"SourceRef":{"Source":"d11"}},"Property":"Year"}},"Right":{"Literal":{"Value":"2013L"}},"ComparisonKind":2}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"DIM_Job Title.Job Title"},"Name":"DIM_Job Title.Job Title"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"-1L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Retention Rate"},"Name":"Measure.Retention Rate"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Average Annual Salary"},"Name":"Measure.Average Annual Salary"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Job Title"},"Name":"DIM_Job Title.Job Title"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"DIM_Job Title.Job Title"},"Name":"DIM_Job Title.Job Title"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["DIM_Job Title.Job Title"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"Job_Title"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"DIM_Job Title"}},"Property":"Job Title"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	partition 'DIM_Job Title' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(File.Contents("D:\PBI Course - Anh Leimer\Project 2 - Linkedin Data Challenge\Dataset\HR Data Analysis_English.xlsx"), null, true),
				    TBL_Employees_Table = Source{[Item="TBL_Employees",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TBL_Employees_Table,{{"Employee ID", type text}, {"Full Name", type text}, {"Job Title", type text}, {"Department", type text}, {"Business Unit", type text}, {"Gender", type text}, {"Ethnicity", type text}, {"Age", Int64.Type}, {"Hire Date", type date}, {"Annual Salary", Int64.Type}, {"Bonus %", type number}, {"Country", type text}, {"City", type text}, {"Exit Date", type date}, {"Latitude", type number}, {"Longitude", type number}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Job Title"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Duplicates", "Job Title", "Job Title - Copy"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Duplicated Column", "Job Title - Copy", Splitter.SplitTextByDelimiter(" ", QuoteStyle.None), {"Job Title.1", "Job Title.2", "Job Title.3"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Job Title.1", type text}, {"Job Title.2", type text}, {"Job Title.3", type text}}),
				    #"Added Job Level" = Table.AddColumn(#"Changed Type1", "Job Level", each if [Job Title] = "Vice President" then [Job Title] else 
				if [Job Title.3] = null and [Job Title.2] <> null then [Job Title.2] else
				if [Job Title.3] = null and [Job Title.2] is null then [Job Title.1] else
				[Job Title.3]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Job Level","II","Analyst",Replacer.ReplaceText,{"Job Level"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value",{"Job Title.1", "Job Title.2", "Job Title.3"}),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Columns", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

