table FACT_Employees
	lineageTag: 86ddd664-ba3c-4b7c-ad37-855db541bb2e

	column 'Full Name'
		dataType: string
		lineageTag: 1f77bd0b-4020-411d-bd35-babfd4d152ba
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 513d22de-dd30-4693-9626-f9ccaabd3149
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = User

	column 'Hire Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d8aba8cc-0a28-4f3c-a022-cce18793e7dd
		summarizeBy: none
		sourceColumn: Hire Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Annual Salary'
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: de2c3320-ccae-4a4e-b2f7-718771f2f2f5
		summarizeBy: average
		sourceColumn: Annual Salary

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Bonus %'
		dataType: double
		lineageTag: f60ff49f-6b9b-47a4-807d-6ddd9a76a197
		summarizeBy: sum
		sourceColumn: Bonus %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Exit Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1755e3cf-e4a3-4cae-802f-fdb33fb4c55c
		summarizeBy: none
		sourceColumn: Exit Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Latitude
		dataType: double
		lineageTag: f774d08d-2cd9-4d94-8bd5-c84dc4d84f98
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 64a864c4-450b-4f41-8d67-3ba29f1aa213
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Age Group Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1264386c-3e7a-46b1-9585-8b50d4a86c13
		summarizeBy: none
		sourceColumn: Age Group Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Gender Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7c95175d-8c3a-4917-a103-97e334b1cb37
		summarizeBy: none
		sourceColumn: Gender Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'City Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ee50414e-ee52-4aab-a073-a40b8526ba29
		summarizeBy: none
		sourceColumn: City Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ethnicity Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ffa450d2-715a-467f-9640-2156d9889a5e
		summarizeBy: none
		sourceColumn: Ethnicity Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Job Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c46583d2-af27-455f-b8d6-d9c8fbc788dd
		summarizeBy: none
		sourceColumn: Job Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Department Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dd5c3fa0-6edf-4d37-905f-f4efe73354b2
		summarizeBy: none
		sourceColumn: Department Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Business Unit Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 660bf732-4eac-4ccf-84be-b74da69a679a
		summarizeBy: none
		sourceColumn: Business Unit Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Employee ID'
		dataType: int64
		formatString: 0
		lineageTag: 4fd39bb5-19dc-4a76-9953-6184ec9e6167
		summarizeBy: count
		sourceColumn: Employee ID

		annotation SummarizationSetBy = Automatic

	column 'Permanency Time'
		dataType: int64
		formatString: 0
		lineageTag: 742c0ebf-fda6-413e-bfa5-23fe54549494
		summarizeBy: sum
		sourceColumn: Permanency Time

		annotation SummarizationSetBy = Automatic

	partition FACT_Employees = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\PBI Course - Anh Leimer\Project 2 - Linkedin Data Challenge\Dataset\HR Data Analysis_English.xlsx"), null, true),
				    TBL_Employees_Table = Source{[Item="TBL_Employees",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(TBL_Employees_Table,{{"Employee ID", type text}, {"Full Name", type text}, {"Job Title", type text}, {"Department", type text}, {"Business Unit", type text}, {"Gender", type text}, {"Ethnicity", type text}, {"Age", Int64.Type}, {"Hire Date", type date}, {"Annual Salary", Int64.Type}, {"Bonus %", type number}, {"Country", type text}, {"City", type text}, {"Exit Date", type date}, {"Latitude", type number}, {"Longitude", type number}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Index",{"Employee ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Index", "Employee ID"}}),
				    #"Added Age Group" = Table.AddColumn(#"Renamed Columns", "Age Group", each if [Age] < 30 then "<30" else if [Age] < 40 then "30-39" else if [Age] < 50 then "40-49" else if [Age] < 60 then "50-59" else ">60"),
				    #"Added Age Group Index" = Table.AddColumn(#"Added Age Group", "Age Group Index", each if [Age Group] = "<30" then 1 else
				if [Age Group] = "30-39" then 2 else
				if [Age Group] = "40-49" then 3 else
				if [Age Group] = "50-59" then 4 else
				5),
				    #"Added Gender Index" = Table.AddColumn(#"Added Age Group Index", "Gender Index", each if [Gender] = "Female" then 1 else
				if [Gender] = "Male" then 2 else
				null),
				    #"Added City Index" = Table.AddColumn(#"Added Gender Index", "City Index", each if [City] = "Phoenix" then 1 else
				if [City] = "Beijing" then	2 else
				if [City] = "Miami" then	3 else
				if [City] = "Chongqing" then 4 else
				if [City] = "Rio de Janerio" then 5 else
				if [City] = "Manaus" then	6 else
				if [City] = "Chicago" then	7 else
				if [City] = "Austin" then	8 else
				if [City] = "Shanghai" then	9 else
				if [City] = "Sao Paulo" then 10 else
				if [City] = "Columbus" then	11 else
				if [City] = "Seattle" then	12 else
				if [City] = "Chengdu" then	13 else
				null),
				    #"Added Ethnicity Index" = Table.AddColumn(#"Added City Index", "Ethnicity Index", each if [Ethnicity] = "Caucasian" then 1 else
				if [Ethnicity] = "Asian" then	2 else
				if [Ethnicity] = "Latino" then	3 else
				if [Ethnicity] = "Black" then 4 else
				null),
				    #"Added Job Index" = Table.AddColumn(#"Added Ethnicity Index", "Job Index", each if [Job Title] = "Director" then 1 else
				if [Job Title] = "Analyst" then 2 else
				if [Job Title] = "Senior Analyst" then 3 else
				if [Job Title] = "Account Representative" then 4 else
				if [Job Title] = "Senior Manager" then 5 else
				if [Job Title] = "Cloud Infrastructure Architect" then 6 else
				if [Job Title] = "System Administrator" then 7 else
				if [Job Title] = "HRIS Analyst" then 8 else
				if [Job Title] = "Analyst II" then 9 else
				if [Job Title] = "Development Engineer" then 10 else
				if [Job Title] = "IT Systems Architect" then 11 else
				if [Job Title] = "Network Architect" then 12 else
				if [Job Title] = "Manager" then 13 else
				if [Job Title] = "Network Administrator" then 14 else
				if [Job Title] = "Controls Engineer" then 15 else
				if [Job Title] = "Field Engineer" then 16 else
				if [Job Title] = "Business Partner" then 17 else
				if [Job Title] = "Service Desk Analyst" then 18 else
				if [Job Title] = "Test Engineer" then 19 else
				if [Job Title] = "Quality Engineer" then 20 else
				if [Job Title] = "Engineering Manager" then 21 else
				if [Job Title] = "Enterprise Architect" then 22 else
				if [Job Title] = "Senior Business Partner" then 23 else
				if [Job Title] = "Computer Systems Manager" then 24 else
				if [Job Title] = "Technical Architect" then 25 else
				if [Job Title] = "Operations Engineer" then 26 else
				if [Job Title] = "Senior Account Representative" then 27 else
				if [Job Title] = "Solutions Architect" then 28 else
				if [Job Title] = "Systems Analyst" then 29 else
				if [Job Title] = "Network Engineer" then 30 else
				if [Job Title] = "Automation Engineer" then 31 else
				if [Job Title] = "IT Coordinator" then 32 else
				if [Job Title] = "Vice President" then 33 else null),
				    #"Added Department Index" = Table.AddColumn(#"Added Job Index", "Department Index", each if [Department] = "Sales" then 1 else
				if [Department] = "Finance" then 2 else
				if [Department] = "Engineering" then 3 else
				if [Department] = "Marketing" then 4 else
				if [Department] = "IT" then 5 else
				if [Department] = "Human Resources" then 6 else
				if [Department] = "Accounting" then 7 else
				if [Department] = "Board Member" then 8 else null),
				    #"Added Business Unit Index" = Table.AddColumn(#"Added Department Index", "Business Unit Index", each if [Business Unit] = "Speciality Products" then 1 else
				if [Business Unit] = "Corporate" then 2 else
				if [Business Unit] = "Manufacturing" then 3 else
				if [Business Unit] = "Research & Development" then 4 else
				if [Business Unit] = "Strategy" then 5 else null),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Business Unit Index",{"Full Name", "Age", "Hire Date", "Annual Salary", "Bonus %", "Exit Date", "Latitude", "Longitude", "Employee ID", "Age Group Index", "Gender Index", "City Index", "Ethnicity Index", "Job Index", "Department Index", "Business Unit Index"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Permanency Time", each [Exit Date] - [Hire Date]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Business Unit Index", Int64.Type}, {"Department Index", Int64.Type}, {"Job Index", Int64.Type}, {"Ethnicity Index", Int64.Type}, {"City Index", Int64.Type}, {"Gender Index", Int64.Type}, {"Age Group Index", Int64.Type}, {"Permanency Time", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

