table Metrics
	lineageTag: 4e442929-e479-4335-9c97-7c241267d820

	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 2903175e-c5cb-43d6-8fd2-3dc9f8a3f4f4
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Impressions
		dataType: int64
		formatString: 0
		lineageTag: 8086a0ff-67a4-4f78-a240-4ac42f648f5b
		summarizeBy: sum
		sourceColumn: Impressions

		annotation SummarizationSetBy = Automatic

	column Clicks
		dataType: int64
		formatString: 0
		lineageTag: d54171c5-bfc2-42dc-9e52-975ed6859cef
		summarizeBy: sum
		sourceColumn: Clicks

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 310de0dd-62a6-43ac-bba0-15ecffba104c
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

	column Conversions
		dataType: int64
		formatString: 0
		lineageTag: 2926f244-7fea-4697-8be9-9bf081c5e0c5
		summarizeBy: sum
		sourceColumn: Conversions

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: d6c00541-daa2-415c-b0cb-88bca42e67df
		summarizeBy: sum
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	column 'Campaign Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5ce597d6-49a4-440f-bb76-e2dde3da92ca
		summarizeBy: none
		sourceColumn: Campaign Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Platform Index'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9eda1448-1e7b-4fbb-8d8b-1ccdecdce478
		summarizeBy: none
		sourceColumn: Platform Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Click-Through-Rate
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 44322eda-cb31-4a48-ad23-d5b8d8c2c58f
		summarizeBy: sum
		sourceColumn: Click-Through-Rate

		annotation SummarizationSetBy = Automatic

	column 'Cost per Click'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: d324c60b-a280-4afc-ab58-d403933e2756
		summarizeBy: sum
		sourceColumn: Cost per Click

		annotation SummarizationSetBy = Automatic

	column 'Conversion Rate'
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: ed458f3d-451e-4c0c-9d9c-ce3190cec46e
		summarizeBy: sum
		sourceColumn: Conversion Rate

		annotation SummarizationSetBy = Automatic

	column 'Cost per Conversion'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 505d5afc-5cbb-44cc-a088-7bec6afe6c2f
		summarizeBy: sum
		sourceColumn: Cost per Conversion

		annotation SummarizationSetBy = Automatic

	column 'Revenue per Conversion'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 310c7dde-7066-4138-b6b4-ad30bd3b418d
		summarizeBy: sum
		sourceColumn: Revenue per Conversion

		annotation SummarizationSetBy = Automatic

	column ROI
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 20bf6660-085f-4240-8cde-aa7ec6705949
		summarizeBy: sum
		sourceColumn: ROI

		annotation SummarizationSetBy = Automatic

	column ROAS
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 525cd94a-b554-45b2-82c7-ff5014844024
		summarizeBy: sum
		sourceColumn: ROAS

		annotation SummarizationSetBy = Automatic

	column 'Impression to Conversion Rate'
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 3a72b92f-5847-40e9-9437-fa221f7ccaa9
		summarizeBy: sum
		sourceColumn: Impression to Conversion Rate

		annotation SummarizationSetBy = Automatic

	column 'Effective Cost per Thousand Impressions '
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: e5efe06a-ebdb-49c5-a222-f78dfd4d8e87
		summarizeBy: sum
		sourceColumn: "Effective Cost per Thousand Impressions "

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: c9449855-f689-45bf-8062-71414ab1b7d6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

	column 'Profit Margin'
		dataType: decimal
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 375cd206-485d-4833-838c-3e72509888d0
		summarizeBy: sum
		sourceColumn: Profit Margin

		annotation SummarizationSetBy = Automatic

	column Traffic
		dataType: string
		lineageTag: d4c1e3d6-4334-4558-86f8-3ab7e87c7525
		summarizeBy: none
		sourceColumn: Traffic

		annotation SummarizationSetBy = Automatic

	partition Metrics = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\PBI Course - Anh Leimer\Project 3\Dataset Media Ad\Media Campaign_edited.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item= if #"Choose dataset" = "Original" then "Old_Sheet1" else "Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Day of Week", type text}, {"Campaign Name", type text}, {"Platform", type text}, {"Impressions", Int64.Type}, {"Clicks", Int64.Type}, {"Cost", type number}, {"Conversions", Int64.Type}, {"Revenue", type number}}),
				    #"Removed Day Of Week" = Table.RemoveColumns(#"Changed Type",{"Day of Week"}),
				    #"Merged to Campaign" = Table.NestedJoin(#"Removed Day Of Week", {"Campaign Name"}, Campaign, {"Campaign"}, "Campaign", JoinKind.LeftOuter),
				    #"Expanded Campaign Index" = Table.ExpandTableColumn(#"Merged to Campaign", "Campaign", {"Index"}, {"Campaign.Index"}),
				    #"Merged to Platform" = Table.NestedJoin(#"Expanded Campaign Index", {"Platform"}, Platform, {"Platform"}, "Platform.1", JoinKind.LeftOuter),
				    #"Expanded Platform Index" = Table.ExpandTableColumn(#"Merged to Platform", "Platform.1", {"Index"}, {"Platform.1.Index"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Platform Index",{"Campaign Name", "Platform"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Campaign.Index", "Campaign Index"}, {"Platform.1.Index", "Platform Index"}}),
				    #"Added Click-Through-Rate" = Table.AddColumn(#"Renamed Columns", "Click-Through-Rate", each [Clicks]/[Impressions]),
				    #"Added Cost per Click" = Table.AddColumn(#"Added Click-Through-Rate", "Cost per Click", each [Cost]/[Clicks]),
				    #"Added Conversion Rate" = Table.AddColumn(#"Added Cost per Click", "Conversion Rate", each [Conversions]/[Clicks]),
				    #"Added Cost per Conversion" = Table.AddColumn(#"Added Conversion Rate", "Cost per Conversion", each [Cost]/[Conversions]),
				    #"Added Revenue per Conversion" = Table.AddColumn(#"Added Cost per Conversion", "Revenue per Conversion", each [Revenue]/[Conversions]),
				    #"Added ROI" = Table.AddColumn(#"Added Revenue per Conversion", "ROI", each [Revenue]/[Cost] - 1),
				    #"Added ROAS" = Table.AddColumn(#"Added ROI", "ROAS", each [Revenue]/[Cost]),
				    #"Added Impression to Conversion Rate" = Table.AddColumn(#"Added ROAS", "Impression to Conversion Rate", each [Conversions]/[Impressions]),
				    #"Added eCPM" = Table.AddColumn(#"Added Impression to Conversion Rate", "Effective Cost per Thousand Impressions ", each [Cost]/[Impressions]),
				    #"Added Profit" = Table.AddColumn(#"Added eCPM", "Profit", each [Revenue]-[Cost]),
				    #"Added Profit Margin" = Table.AddColumn(#"Added Profit", "Profit Margin", each [Profit]/[Revenue]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Profit Margin",{{"Revenue", Currency.Type}, {"Cost per Click", Currency.Type}, {"Cost per Conversion", Currency.Type}, {"Revenue per Conversion", Currency.Type}, {"Effective Cost per Thousand Impressions ", Currency.Type}, {"Profit", Currency.Type}, {"ROAS", Currency.Type}, {"Cost", Currency.Type}, {"Click-Through-Rate", Currency.Type}, {"Conversion Rate", Currency.Type}, {"ROI", Currency.Type}, {"Impression to Conversion Rate", Currency.Type}, {"Profit Margin", Currency.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

