table Calendar
	lineageTag: 23bbaf44-36a4-4a30-86e2-2b4c94a50a30
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: d91c6aef-63e0-4e98-94fe-933f4a4e05ba
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e83709c3-518b-43f3-8fd2-7b8382598c6c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 2d3db67b-a2a5-4fb1-9f96-749780b85a6e
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Year S'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Year S'
		dataType: int64
		formatString: 0
		lineageTag: 8cc4e692-2326-4280-b759-cde8b2ec3dfe
		summarizeBy: none
		sourceColumn: Month Year S

		annotation SummarizationSetBy = Automatic

	column 'Week Day'
		dataType: string
		lineageTag: 2cca3a33-da0e-4c30-b1ab-749dc91509a2
		summarizeBy: none
		sourceColumn: Week Day
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 02f67e4d-2506-4ee3-bd3d-825b2695187b
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: e350ac26-f4a1-476b-9981-32424c834a81
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: 896f8670-a96f-4e92-882a-13c8666a849a
		summarizeBy: none
		sourceColumn: Week of Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name Full'
		dataType: string
		lineageTag: d408a98b-a478-4b5b-8cd7-00196ed73821
		summarizeBy: none
		sourceColumn: Month Name Full
		sortByColumn: 'Month Year S'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: eab285b0-ca67-4c85-83c4-21b852a55b6a

		level Year
			lineageTag: 6f73882a-fcbf-4742-bb31-ea7daba91443
			column: Year

	partition Calendar = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let 
				// Create parameter 
				    StartDate = List.Min(FACT_Transaction[Transaction Date]),
				    //StartDate = #date(2023,1,1),
				    EndDate = List.Max(FACT_Transaction[Transaction Date]),
				    Step = Duration.Days(EndDate - StartDate)+1, 
				// Create the List of date
				    Source = List.Dates(StartDate,Step, #duration(1,0,0,0)), 
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Date"}}),
				// Create additional columns 
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Quarter Year" = Table.AddColumn(#"Inserted Quarter", "Quarter Year", each Text.Combine({"Q", Text.From([Quarter], "en-US"), " ", Text.From([Year], "en-US")}), type text), 
				    #"Inserted Month" = Table.AddColumn(#"Inserted Quarter Year", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Text.Start(Date.MonthName([Date]),3), type text),
				    #"Added Month Name Full" = Table.AddColumn(#"Inserted Month Name", "Month Name Full", each Date.MonthName([Date])),
				    #"Inserted Month Year" = Table.AddColumn(#"Added Month Name Full", "Month Year", each Text.Combine({[Month Name], " ", Text.From([Year], "en-US")}), type text),
				    #"Inserted Month Year S" = Table.AddColumn(#"Inserted Month Year", "Month Year S", each Text.Combine({Text.From([Year], "en-US"), Text.PadStart(Text.From([Month], "en-US"), 2, "0")}), type text),
				    #"Inserted End of Month" = Table.AddColumn(#"Inserted Month Year S", "End of Month", each Date.EndOfMonth([Date])),
				    #"Inserted Week Day Name" = Table.AddColumn(#"Inserted End of Month", "Week Day", each Text.Start(Date.DayOfWeekName([Date]),3), type text),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Week Day Name", "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Inserted Day" = Table.AddColumn(#"Inserted Day of Week", "Day", each Date.Day([Date]), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Day", "Week of Month", each Date.WeekOfMonth([Date]), Int64.Type),
				    #"Inserted Week of Month W" = Table.AddColumn(#"Inserted Week of Month", "Week", each Text.Combine({"W", Text.From([Week of Month], "en-US")}), type text),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Week of Month W", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    #"Inserted Week of Year W" = Table.AddColumn(#"Inserted Week of Year", "Week of Year W", each Text.Combine({"W", Text.From([Week of Year], "en-US")}), type text),
				    #"Added Fiscal Month" = Table.AddColumn(#"Inserted Week of Year W", "Fiscal Month", each if Date.Month([Date]) <= 3 then Date.Month([Date]) + 9 else Date.Month([Date]) - 3),
				    #"Added Fiscal Year" = Table.AddColumn(#"Added Fiscal Month", "Fiscal Year", each if Date.Month([Date]) <= 3 then Date.Year([Date]) else Date.Year([Date]) + 1),
				    #"Added Fiscal Quarter" = Table.AddColumn(#"Added Fiscal Year", "Fiscal Quarter", each Number.RoundUp([Fiscal Month]/3)),
				    #"Added IsWeekend" = Table.AddColumn(#"Added Fiscal Quarter", "IsWeekend", each if [Day of Week] >= 5 then 1 else 0),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added IsWeekend",{{"Fiscal Quarter", Int64.Type}, {"Fiscal Year", Int64.Type}, {"Fiscal Month", Int64.Type}, {"End of Month", type date}, {"Month Year S", Int64.Type}, {"Month Name Full", type text}, {"IsWeekend", Int64.Type}}),
				    #"Columns removed by Measure Killer"= Table.SelectColumns(#"Changed Type1",{"Day of Week","Date","Month Name Full","Year","Week of Month","Month Name","Month Year S","Day","Week Day"})
				in
				    #"Columns removed by Measure Killer"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

