table DIM_Product
	lineageTag: 95a6d238-8168-4af1-a618-b8ae1b44f398

	column 'Product Id'
		dataType: int64
		formatString: 0
		lineageTag: 23013ba1-3676-404e-bf83-7cbd59907193
		summarizeBy: none
		sourceColumn: Product Id

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 0b32aeea-c316-4d2e-8251-3f1b1b1fcc8a
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"DIM_Product","TableItemName":"Product (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'Product Category'
		dataType: string
		lineageTag: c2f7d4e4-e4fe-4cb3-94f1-d7b21b3aa172
		summarizeBy: none
		sourceColumn: Product Category

		annotation SummarizationSetBy = Automatic

	column 'Product Type'
		dataType: string
		lineageTag: 7700c969-13d9-4a1f-ae1a-4c9008ebed68
		summarizeBy: none
		sourceColumn: Product Type

		annotation SummarizationSetBy = Automatic

	/// Clusters for Product
	column 'Product (clusters)' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE(
					'ClusterMappingTable'[ClusterId],
					'ClusterMappingTable'[Product],
					'DIM_Product'[Product]
				)
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		lineageTag: 10a68904-92ce-4e35-8c31-2b43fcbc77a4
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "DIM_Product"
				          }
				        },
				        "Property": "Product"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"DIM_Product"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Product"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"f","Entity":"FACT_Transaction"},{"Name":"d","Entity":"DIM_Product"},{"Name":"m","Entity":"Measure"},{"Name":"c","Entity":"Calendar"}],"Where":[{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"c"}},"Property":"Month Name Full"}}],"Values":[[{"Literal":{"Value":"'June'"}}]]}}}],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"DIM_Product.Product"},"Name":"DIM_Product.Product"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"4L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Aggregation":{"Function":1,"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"Transaction Qty"}}},"Name":"Sum(FACT_Transaction.Transaction Qty)"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"Product"},"Name":"DIM_Product.Product"}},{"Role":"Attribute","Expression":{"Measure":{"Expression":{"SourceRef":{"Source":"m"}},"Property":"Avg Unit Price"},"Name":"Measure.Average Unit Price"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"DIM_Product.Product"},"Name":"DIM_Product.Product"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["DIM_Product.Product"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"Product"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"DIM_Product"}},"Property":"Product"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	partition DIM_Product = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Accelerate Career with Power BI\Project 1 - Coffee Shop\1. Dataset\Product.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_detail", type text}, {"product_category", type text}, {"product_type", type text}}),
				    #"Replace Headers" = Table.TransformColumnNames(#"Changed Type", each Text.Replace(_,"_"," ")),
				    #"Capitalize Headers" = Table.TransformColumnNames(#"Replace Headers", Text.Proper),
				    #"Renamed Columns" = Table.RenameColumns(#"Capitalize Headers",{{"Product Detail", "Product"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

